import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>IC Solutions-Yashodhan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="">

      </header>

      <main className="">
  
      </main>

      <footer className="">

      </footer>
    </div>
  )
}
