import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>IC Solutions-Yashodhan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className="sticky top-0 z-50 bg-white flex justify-between items-center p-4 px-12 shadow-md">
        <Image
          src="/develup_logo.png"
          alt="hearder-image"
          height="30"
          width="130"
          loading="lazy"
        />

        <form className="border-2 p-1 border-gray-400 focus-within:border-black rounded-full min-w-max w-1/3">
          <input
            type="text"
            placeholder="Search for courses"
            className="outline-none px-2 flex-grow"
          />
        </form>
      </header>

      <main className="">
        {/*Section#1 */}
        <div className="bg-gray-300 flex flex-col items-center space-y-2 border-2 lg:space-x-4 py-24">
          <p className="text-2xl lg:text-5xl text-white mb-24">
            Make your future, today
          </p>
          <div className="flex flex-col items-center gap-2 lg:flex-row ">
            <button className="bg-gray-600 px-4 py-2 text-white text-sm hover:bg-gray-800">
              I WANT A JOB
            </button>
            <button className="bg-gray-600 px-4 py-2 text-white text-sm hover:bg-gray-800">
              I WANT A JOB
            </button>
          </div>
        </div>

        {/*Section#2 */}
        <div className="flex items-center justify-center">

          <div className="flex items-center lg:overflow-hidden overflow-scroll scrollbar-hide m-4">
            <div className="bg-gray-500 text-white m-6 p-8 shadow-md min-w-max max-w-max overscroll-x-auto">
              <p className="text-3xl font-bold text-white text-center">28739</p>
              <p className="text-sm font-thin text-white text-center">
                No of courses offered
              </p>
            </div>

            <div className="bg-gray-500 text-white m-6 p-8 shadow-md min-w-max max-w-max overscroll-x-auto">
              <p className="text-3xl font-bold text-white text-center">158</p>
              <p className="text-sm font-thin text-white text-center">
                No of training offered
              </p>
            </div>

            <div className="bg-gray-500 text-white m-6 p-8 shadow-md min-w-max max-w-min overscroll-x-auto">
              <p className="text-3xl font-bold text-white text-center">185</p>
              <p className="text-sm font-thin text-white text-center">
                No of jobs available
              </p>
            </div>

            <div className="bg-gray-500 text-white m-6 p-8 shadow-md min-w-max max-w-min overscroll-x-auto">
              <p className="text-3xl font-bold text-white text-center">158</p>
              <p className="text-sm font-thin text-white text-center">
                No of career support
              </p>
            </div>

            <div className="bg-gray-500 text-white m-6 p-8 shadow-md min-w-max max-w-min overscroll-x-auto">
              <p className="text-3xl font-bold text-white text-center">2.5L</p>
              <p className="text-sm font-thin text-white text-center">
                No of candidates enrolled
              </p>
            </div>
          </div>

        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
