import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>IC Solutions-Yashodhan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className="static flex justify-between items-center p-4 px-12 shadow-md">
        <Image
          src="/develup_logo.png"
          alt="hearder-image"
          height="30"
          width="130"
          loading="lazy"
        />

        <form className="border-2 p-1 border-gray-400 focus-within:border-black rounded-full min-w-max w-1/3">
          <input
            type="text"
            placeholder="Search for courses"
            className="outline-none px-2 flex-grow"
          />
        </form>
      </header>

      <main className=""></main>

      <footer className=""></footer>
    </div>
  );
}
